[mgr]
prepend_keymap = [
    { on = "`", run = "plugin command", desc = "Yazi command prompt" },
    { on = ["c", "d"], run = "cd --interactive", desc = "Change directory prompt" },
    { on = "<F7>", run = "create --dir", desc = "Create directory" },
    { on = "<F8>", run = "create", desc = "Create file or directory" },
    { on = ["c", "w"], run = "rename --cursor=before_ext", desc = "Rename selected files" },
    { on = "d", run = "yank --cut", desc = "Cut file" },
    { on = "z", run = "plugin fzf", desc = "Fzf jump" },
    { on = "l", run = "plugin smart-enter", desc = "Enter the directory or open the file" },
    { on = ["<Tab>", "a"], run = "toggle_all --state=on", desc = "Select all files" },
    { on = ["<Tab>", "n"], run = "toggle_all --state=off", desc = "Deselect all files" },
]
