#!/bin/sh

if [ -f "$1" ]; then
    content="@$1"
else
    content="$1"
fi

url="$(curl -sF "c=$content" -w "%{redirect_url}" "https://ptpb.pw/?r=1" -o /dev/null)"
if [ -z "$url" ]; then
    notify-send PTPB "Error while sending paste. Code: $?"
else
    xclip -selection "clipboard" <<< $url
    notify-send PTPB "Pastebin succesful. URL: $url"
fi
