#!/bin/sh

if [ -z $1 ] || [ ! -f $1 ]; then
    echo "File does not exist!"
    exit 1
fi

filename=$(basename $1)
notify_bg="#db7f00"
notify_fg="#000000"
notify_success="URL for '$filename' has been copied to clipboard."
notify_fail="File already exist in Dropbox!"

if [ -z "$HOME/Dropbox/Public/$1" ] || [ ! -f "$HOME/Dropbox/Public/$1" ]; then
    cp $1 ~/Dropbox/Public/
    dropbox-cli puburl ~/Dropbox/Public/$filename | xclip -selection "clipboard"
    notify-send -h string:bgcolor:$notify_bg -h string:fgcolor:$notify_fg SHARE "$notify_success"
else
    notify-send -h string:bgcolor:$notify_bg -h string:fgcolor:$notify_fg SHARE "$notify_fail"
fi
