#!/usr/bin/env python3

import datetime
import time
import sys

current_time = datetime.datetime.now().strftime('%d-%m-%y %H:%M:%S')
print('Stopwatch start: {}'.format(current_time))
seconds_from_start = 0
while True:
    sys.stdout.write(
        '\rCurrent time: {:.2f} minutes'.format(seconds_from_start / 60)
    )
    sys.stdout.flush()
    seconds_from_start += 1
    time.sleep(1)
