#!/bin/sh

if [[ ! -z $1 ]]; then
    stream_name=$1
else
    stream_name=""
fi

if [[ -z $2 ]]; then
    quality="best"
else
    quality=$2
fi

if [[ ! -z $stream_name ]]; then
    notify-send --app-name "Streamlink" "TWITCH" "Launching $1 stream..."
    output=$(streamlink -a "--title 'Twitch - $stream_name' {filename}" --loglevel error https://twitch.tv/$stream_name $quality)
    if [[ $? != 0 ]]; then
        notify-send --app-name "Streamlink" "TWITCH" "$output"
    fi
else
    notify-send --app-name "Streamlink" "TWITCH" "No stream name given."
fi
