# History file and size
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# History settings
setopt HIST_VERIFY
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS

# Complete aliases
setopt COMPLETE_ALIASES

# Set key binding to emacs (no insert/normal mode)
bindkey -e

# Prevent pasted tab to perform completion
zstyle ':completion:*' insert-tab pending
# default to file completion
zstyle ':completion:*' completer _expand _complete _files _correct _approximate
# Completion list behaves like menu selecting
zstyle ':completion:*' menu select
autoload -Uz compinit
compinit

# Bind home key
bindkey '^[[H' beginning-of-line
bindkey '^[[1~' beginning-of-line
# Bind end key
bindkey '^[[F' end-of-line
bindkey '^[[4~' end-of-line
# Bind delete key
bindkey '^[[3~' delete-char
# Bind page up key
bindkey '^[[5~' beginning-of-buffer-or-history
# Bind page down key
bindkey '^[[6~' end-of-buffer-or-history
# Bind Ctrl + R shortcut
bindkey '^R' history-incremental-search-backward

# Turn on colors
autoload -U colors && colors

# Set up a custom prompt with right prompt
# This is used only if Powerline is not
PROMPT="[%{$fg[green]%}%n@%m %1~%{$reset_color%}]%# "
RPROMPT="[%?]"

# Set virtual env for python
export VIRTUALENVWRAPPER_PYTHON='/usr/bin/python'
export WORKON_HOME='~/Development/Python_environments/'
source /usr/bin/virtualenvwrapper.sh

# Set fish like syntax highligthing
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Aliases
source $HOME/Development/dotfiles/zsh/aliases.zsh

# Setup correct terminal inside tmux
export TERM=xterm-256color
if [[ -n "$TMUX" ]]; then
    export TERM=screen-256color
fi

# Use Neovim as text editor of choice
export EDITOR=nvim

# User powerline only outside of Midnigh Commander
if ps $PPID | grep mc; then
    PROMPT="[%{$fg[green]%}%n@%m %1~%{$reset_color%}]%# "
    RPROMPT=""
else
    source ~/.local/lib/python3.5/site-packages/powerline/bindings/zsh/powerline.zsh
fi
