# History file and size
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# History settings
setopt HIST_VERIFY
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS

# Complete aliases
setopt COMPLETE_ALIASES

# Set key binding to emacs (no insert/normal mode)
bindkey -e

autoload -Uz compinit colors
compinit
colors

# Automaticaly find new executables in $PATH
zstyle ':completion:*' rehash true

typeset -A key
key[Home]=${terminfo[khome]}
key[End]=${terminfo[kend]}
key[Insert]=${terminfo[kich1]}
key[Delete]=${terminfo[kdch1]}
key[Up]=${terminfo[kcuu1]}
key[Down]=${terminfo[kcud1]}
key[Left]=${terminfo[kcub1]}
key[Right]=${terminfo[kcuf1]}
key[PageUp]=${terminfo[kpp]}
key[PageDown]=${terminfo[knp]}

bindkey "$(tput khome)" beginning-of-line
bindkey "$(tput kend)" end-of-line
bindkey "$(tput kdch1)" delete-char
bindkey "$(tput kpp)" beginning-of-buffer-or-history
bindkey "$(tput knp)" end-of-buffer-or-history
bindkey '^R' history-incremental-search-backward

# Set up a custom prompt with right prompt
# This is used only if Powerline is not
PROMPT="[%{$fg[green]%}%n@%m %1~%{$reset_color%}]%# "
RPROMPT="[%?]"

# Set virtual env for python
export VIRTUALENVWRAPPER_PYTHON='/usr/bin/python'
export WORKON_HOME='~/Development/Python_environments/'
source /usr/bin/virtualenvwrapper.sh

# Set fish like syntax highligthing
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Aliases
source $HOME/Development/dotfiles/zsh/aliases.zsh

# Use Neovim as text editor of choice
export EDITOR=nvim

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
